import type { AppConfig, CategoryDefinition, CodeDefinition, KpiDefinition } from "../types";

/**
 * Initial business configuration. This seeds the application on first run and
 * is fully maintainable afterwards through the Admin UI — nothing here is
 * referenced directly by dashboard components.
 */

const INITIAL_CODES: [string, string, string][] = [
  ["DTEC", "Digital Time entry Cockpit Simplified", "IP"],
  ["SSYN", "Scalesync Simplified", "IP"],
  ["TPSI", "Trade program Simplified", "IP"],
  ["VCSI", "Vendor Certificate Simplified", "IP"],
  ["MCSI", "Maintenance checklist Simplified", "IP"],
  ["RFSI", "RF Simplified", "IP"],
  ["CTOS", "Cost to serve", "IP"],
  ["CBPA", "CBP", "Accelerator"],
  ["MISC", "Miscellaneous", "Miscellaneous"],
  ["KTRA", "Knowledge Transfer", "Knowledge Transfer"],
  ["PCSI", "Procurement Cockpit Simplified", "IP"],
  ["LEAR", "Learning", "Learning"],
  ["LEAV", "Leave", "Leave"],
  ["CELB", "Celebrations", "Celebrations"],
  ["HRMS", "HR Meetings", "HR Meetings"],
  ["INTM", "Internal meetings", "Internal Meetings"],
  ["FIGL", "FI GL Upload", "IP"],
  ["ARAP", "AR AP AGING", "IP"],
  ["GLIP", "GLOBAL IP", "IP"],
  ["TRAI", "Trainings", "Trainings"],
  ["GLTR", "Glasswing Training", "IP"],
  ["MATR", "Makira Training", "IP"],
  ["BTRC", "Batch Recall", "Accelerator"],
  ["MSLM", "Material Shelf Life Management", "Accelerator"],
  ["1099", "1099 Tax Report", "Accelerator"],
  ["VPAP", "Vendor Portal app", "IP"],
  ["MSRA", "Material Shortage Report Accelerator", "Accelerator"],
  ["UDRA", "UDReversal", "Accelerator"],
  ["AIPO", "AI POCs", "IP"],
  ["OPOC", "Other POCs", "IP"],
  ["CONV", "Conversion", "Conversion"],
  ["AMSS", "AMS Support", "AMS Support"],
  ["IPSS", "IP Support", "IP Support"],
  ["MACE", "Makira Customer Engagement (Customer Billable)", "IP"],
  ["GACE", "Glasswing Customer Engagement (Customer Billable)", "IP"],
  ["IPMA", "IP Maintenance", "Accelerator"],
  ["IDLE", "IDLE Time", "IDLE Time"],
  ["SAPP", "Sapphire", "Accelerator"],
  ["SCRU", "Scrum calls", "Scrum calls"],
  ["RNDP", "RND", "RND"],
  ["1AIL", "AI Launchpad", "IP"],
  ["1AIN", "AI Navigator", "IP"],
  ["AISR", "AI Sales Research", "IP"],
  ["1ACC", "AMS Consulting Copilot", "IP"],
  ["GAIA", "Gen AI Amplifier", "IP"],
  ["2PC", "Partner Co-Pilot", "IP"],
  ["1SAI", "Sherlock AI", "IP"],
  ["1SIC", "Strategic Insights Copilot", "IP"],
  ["TBAI", "Ticketing BOT AI", "IP"],
  ["AICS", "AI Prototype | John Boos Customer Service", "IP"],
  ["MRPA", "MRP Exceptions Accelerated", "Accelerator"],
  ["02PH", "PeopleHub", "IP"],
];

const INITIAL_CATEGORIES: [string, boolean][] = [
  // [name, countsAsProductive]
  ["IP", true],
  ["Accelerator", true],
  ["Miscellaneous", false],
  ["Knowledge Transfer", false],
  ["Learning", false],
  ["Leave", false],
  ["Celebrations", false],
  ["HR Meetings", false],
  ["Internal Meetings", false],
  ["Trainings", false],
  ["Conversion", false],
  ["AMS Support", false],
  ["IP Support", false],
  ["IDLE Time", false],
  ["Scrum calls", false],
  ["RND", false],
  ["Unknown", false],
];

const INITIAL_KPIS: Omit<KpiDefinition, "enabled">[] = [
  {
    id: "total_hours",
    name: "Total Hours",
    description: "Sum of hours across all rows in scope",
    formula: "SUM(hours)",
    format: "hours",
    category: "primary",
  },
  {
    id: "billable_hours",
    name: "Billable Hours",
    description: "Sum of hours on rows classified billable by the WBS rules",
    formula: "SUM(hours WHERE isBillable)",
    format: "hours",
    category: "primary",
  },
  {
    id: "billable_percentage",
    name: "Billable %",
    description: "Billable hours as a share of total hours (never an average of individual percentages)",
    formula: "billable_hours / total_hours × 100",
    format: "percent",
    category: "primary",
  },
  {
    id: "ip_hours",
    name: "IP Hours",
    description: "Sum of hours on development rows whose code maps to a productive 'IP' category",
    formula: "SUM(hours WHERE category = 'IP')",
    format: "hours",
    category: "primary",
  },
  {
    id: "accelerator_hours",
    name: "Accelerator Hours",
    description: "Sum of hours on development rows whose code maps to the 'Accelerator' category",
    formula: "SUM(hours WHERE category = 'Accelerator')",
    format: "hours",
    category: "primary",
  },
  {
    id: "productive_hours",
    name: "Productive Hours",
    description: "Billable hours plus hours in productive development categories; no row is counted twice",
    formula: "billable_hours + SUM(hours WHERE category is productive)",
    format: "hours",
    category: "primary",
  },
  {
    id: "productive_percentage",
    name: "Productive %",
    description: "Productive hours as a share of total hours",
    formula: "productive_hours / total_hours × 100",
    format: "percent",
    category: "secondary",
  },
  {
    id: "ip_delivery_hours",
    name: "IP Delivery Hours",
    description: "Total hours logged by configured IP Delivery Team members",
    formula: "SUM(hours WHERE team = 'IP Delivery Team')",
    format: "hours",
    category: "secondary",
  },
  {
    id: "development_team_hours",
    name: "Development Team Hours",
    description: "Total hours logged by Development Team members",
    formula: "SUM(hours WHERE team = 'Development Team')",
    format: "hours",
    category: "secondary",
  },
  {
    id: "development_hours",
    name: "Development Hours",
    description: "Sum of hours on rows matching the development WBS rules",
    formula: "SUM(hours WHERE isDevelopment)",
    format: "hours",
    category: "secondary",
  },
];

export const DEFAULT_CONFIG: AppConfig = {
  version: "v1.0",
  updatedAt: "2026-08-17T00:00:00.000Z",
  billableRules: {
    allowedPrefixes: ["0004A", "0004C"],
    nextCharacterMustNotBe: ["9"],
    excludedWbs: ["0004A99999-008.02-900", "0004A99999-008.02-901"],
  },
  developmentRules: {
    allowedPrefixes: ["0004I"],
  },
  codes: INITIAL_CODES.map(
    ([code, description, category]): CodeDefinition => ({
      code,
      description,
      category,
      active: true,
    }),
  ),
  categories: INITIAL_CATEGORIES.map(
    ([name, productive]): CategoryDefinition => ({ name, productive, active: true }),
  ),
  teams: [
    {
      id: "ip-delivery",
      name: "IP Delivery Team",
      members: [
        "Sai Bhargav Sabbani",
        "Rishabh Kainthola",
        "Nagaraj Kandukuri",
        "Aditya Shukla",
      ],
      catchAll: false,
      active: true,
    },
    {
      id: "development",
      name: "Development Team",
      members: [],
      catchAll: true,
      active: true,
    },
  ],
  kpis: INITIAL_KPIS.map((k) => ({ ...k, enabled: true })),
  columnMapping: {
    wbs: "WBS Element",
    employee: "Name of Employee or Applicant",
    hours: "Number (unit)",
    shortText: "Short Text",
    date: "Date",
  },
};
